# Simplyblock CSI StorageClasses for SkyForge
# NVMe-oF block storage with enterprise performance

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: northstack-block-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    description: "High-performance NVMe storage for databases and OLTP workloads"
provisioner: csi.simplyblock.io
parameters:
  storagePool: nvme-fast
  iops: "100000"
  throughput: "1000"
  encryption: "true"
  replication: "3"
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: northstack-block-standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    description: "Standard NVMe storage for general workloads"
provisioner: csi.simplyblock.io
parameters:
  storagePool: nvme-standard
  iops: "10000"
  throughput: "250"
  encryption: "true"
  replication: "2"
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: northstack-block-economy
  annotations:
    description: "Economy NVMe storage for dev/test workloads"
provisioner: csi.simplyblock.io
parameters:
  storagePool: nvme-economy
  iops: "3000"
  throughput: "125"
  encryption: "true"
  replication: "2"
  fsType: ext4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
